seuros/capistrano-puma

- lib/capistrano/templates/nginx_conf.erb
The current regex requires unix://, which doesn't really make sense for unix sockets. A single forward slash is all that's required, and all that Puma and Nginx expect. In fact, it's even the default value for `fetch(:puma_bind)`.
> Allow unix:/foo/ socket URLs

- lib/capistrano/tasks/puma.cap
I was faced with a conflict between phased restart and puma's preload_app.
```ruby
set :puma_threads, [4, 4]
set :puma_workers, 2
set :puma_preload_app, true
```
With this config gem invokes `phased-restart`, which is not recommended for preload_app.
My changes makes gem not to rely only on `puma_workers`, but also on `puma_preload_app`, to decide what restart method  to be invoked.
> Fix smart_restart task to check if puma preloads app

- README.md
Updated minor typo in Nginx config example path, updated inline comments to be consistent with other comments in README
> Update Typo in README

- README.md
- lib/capistrano/tasks/puma.cap
- lib/capistrano/templates/puma.rb.erb
In the case puma __preload_app!__ is incompatible with __puma_prune_bundler__ [https://github.com/puma/puma/blob/master/examples/config.rb#L132]()
and puma will crash because of bundle context not switch between each capistrano deployment (even with the `puma:restart`, which is using by default with __preload_app__)
> /opt/ruby21/share/gems/gems/bundler-1.8.3/lib/bundler/definition.rb:22:in `build': /path/to/Gemfile/with/deleted/capistrano/deleted/path/20150303095846/Gemfile not found (Bundler::GemfileNotFound)
To make sure bundler is automatically switched between each deploy and do the right thing for __preload_app__ or not.
@behe any idea?
> bundler prune should be automatically detect

- lib/capistrano/tasks/puma.cap
Since the default number of workers is zero, preload_app default config should be false
After reading the [puma's README](https://github.com/puma/puma/blob/master/README.md), I noticed they don't recommend to use *preload_app* if you're not using workers. I think it'd better to set the default to false.
> General rule is to use preload_app when your workers die often and need fast starts. If you don’t have many workers, you probably should not use preload_app
> Set :puma_preload_app to false

- lib/capistrano/tasks/monit.cap
Not reloading monit will cause monit to complain with the error `monit: action failed -- There is no service by that name`
> Reload Monit after uploading any monit configuration

- lib/capistrano/templates/puma.rb.erb
According to https://github.com/puma/puma/issues/728. As @evanphx said, there is no need of `on_worker_boot ` block when using `prune_bundler`.
> Don't need establish connection block if `puma_preload_app' set to false

- lib/capistrano/tasks/puma.rake
The variable role was not being passed to the block, causing it to look for role method in capistrano
> Added fix for wrong arguments on puma stop

- README.md
- lib/capistrano/tasks/puma.rake
- lib/capistrano/templates/puma_monit.conf.erb
Same as https://github.com/seuros/capistrano-sidekiq/pull/104
We don't need to explicitly specify the bundle exec statement(actually, we shouldn't).
The best practice is add the binaries to the bundle_bins array.
With following the best practice, the user can easily to custom the execution command, for example, I am going to use the dotenv executable to launch the puma. I can add an additive task like this:
```
namespace :bundler do
task :map_bins do
fetch(:bundle_bins).each do |command|
SSHKit.config.command_map.prefix[command.to_sym].push('dotenv')
end
end
end
```
> Use SSHKit command_map

- lib/capistrano/puma/version.rb
- lib/capistrano/tasks/puma.rake
To override this change in puma 2.12.0 
" * Make pumactl load config/puma.rb by default"
which causes issue #120
> Issue #120 -- explicitly pass the config file location to pumactl

- lib/capistrano/tasks/puma.rake
- lib/capistrano/tasks/workers.rake
The README mentions `set :puma_user, 'myuser'`, but the setting is ignored. It only works as a per-role setting: `role :app, %w(puma1 puma1), puma_user: 'myuser'`. This PR allows both to work, giving giving higher priority to the per-role setting.
> Respect the global puma_user setting

- README.md
Default value of puma_preload_app was changed false via 013bb17ce0c79bfd3e40bf9648ddb819d9f6e58b
https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/puma.rake#L19
> Fix README: default value of puma_preload_app is false

- lib/capistrano/templates/nginx_conf.erb
Without this change `nginx -t` warns about `conflicting server name "" on 0.0.0.0:80` when running multiple SSL enabled apps. Visiting a configured domain via HTTP results in a 502 Bad Gateway error.
> Add server_name to the http->https redirection server block

- lib/capistrano/tasks/monit.rake
In puma monit task
Added call to create the template, when there is no monitoring added
> Fix puma:monit task for first deployment

- lib/capistrano/tasks/puma.rake
Now, when I try `puma:start` command for a server already running puma, cause this error.
```
`add_unix_listener': There is already a server bound to: /path/to/puma.sock (RuntimeError)
```
I fixed to skip puma start command if found puma process.
```sh
$ bundle exec cap puma:start # first
00:00 puma:start
using conf file /path/to/puma.rb
01 bundle exec puma -C /path/to/puma.rb --daemon
01 * Pruning Bundler environment
01 [13747] Puma starting in cluster mode...
01 [13747] * Version 3.7.1 (ruby 2.4.0-p0), codename: Snowy Sagebrush
01 [13747] * Min threads: 0, max threads: 16
01 [13747] * Environment: staging
01 [13747] * Process workers: 1
01 [13747] * Phased restart available
01 [13747] * Listening on unix:///path/to/puma.sock
01 [13747] * Daemonizing...
✔ 01 dev@XXX.XXX.XXX.XXX 0.517s
$ …
```
> Skip puma start command if puma is running

- README.md
- lib/capistrano/tasks/puma.rake
- lib/capistrano/templates/puma.rb.erb
Allows to set `set :puma_daemonize, true` config to use Puma `daemonize` instruction.
This can be useful when not using Puma's `--daemon` option or through `pumactl`.
> Add 'daemonize' config

- lib/capistrano/puma/nginx.rb
It looks like in 3.0.1 with explicit plugin loading the `:application` var is not set at the plugin loading stage.
> Fix vars loading issue during plugin initialization

- README.md
- lib/capistrano/puma.rb
- lib/capistrano/puma/workers.rb
- lib/capistrano/tasks/workers.rake
- lib/capistrano/templates/puma.rb.erb
These are some minor issues that I encountered while digging into some errors that happened while trying to fix #208... since they are very minor, I don't think it's necessary to create more issues.
In any case, even if this PR is not merged, take them as reference for possible issues.
* Missing variables for `puma_tag` and `puma_control_app`. Added to the README.
* Included `PumaCommon` in `Puma::Workers` class definition (`puma:workers:count` didn't work because of `method_missing: puma_user`)
* Better logic in the `workers.rake` tasks. Capturing the pidfile with backticks inside a string wouldn't work as intended, it's better to cat the pidfile first and then interpolate inside the grep.
* Indentation for the `tag` field in the puma template was off.
> Minor fixes

- README.md
The commands `cap puma:config` and `cap puma:nginx_config` will fail with the following error message, if the stage (e.g. production) is ommited:
> Stage not set, please call something such as `cap production deploy`, where production is a stage you have defined.
> Add stage to cap commands

- README.md
- lib/capistrano/templates/nginx_conf.erb
If your SSL certificates are located somewhere else than
`/etc/ssl/certs/` and `/etc/ssl/private/` respectively, you can
use the options `:nginx_ssl_certificate` and
`:nginx_ssl_certificate_key` to specify their location.
> Add option to specify the location of SSL certificates

- lib/capistrano/tasks/monit.rake
Hi @seuros,
I just started to use Monit.
I noticed there is task puma:monit:config which is called when there is no process to monitor.
The task reloads Monit which is fine but it seems like Monit doesn't have enough time to fully reload.
That is why I have the following error:
```
00:20 puma:monit:monitor
01 sudo /usr/bin/monit monitor puma_orip_bot_staging
01 [sudo] password for deployer:
01
01 There is no service named "puma_orip_bot_staging"
00:20 puma:monit:config
Uploading /tmp/monit.conf 100.0%
01 sudo mv /tmp/monit.conf /etc/monit/conf.d/puma_orip_bot_staging.conf
01 [sudo] password for deployer:
01
✔ 01 deployer@xxx.xxx.xxx.xxx 0.058s
02 sudo /usr/bin/monit reload
02 [sudo] password for deployer:
02
02 Reinitializing monit daemon
02
✔ 02 deployer@xxx.xxx.xxx.xxx 0.059s
03 sudo …
```
> Wait for Monit to be reloaded

- lib/capistrano/puma.rb
- lib/capistrano/puma/monit.rb
This PR should fix the following issues:
* When deploying as a different user than the one that must run ```puma```
> NoMethodError: undefined method `as' for #<Capistrano::Puma:0x007fde85295840>
which is reported here: https://github.com/seuros/capistrano-puma/issues/229
* When using monit to monitor the puma process
> Warning: `execute' should be wrapped in an `on' scope in /Users/daniel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/dsl.rb:38.
> 
>   task :example do
>     on roles(:app) do
>       execute 'whoami'
>     end
>   end
> 
> (Backtrace restricted to imported tasks)
> cap aborted!
> SSHKit::Runner::ExecuteError: Exception while executing on host *: Exception while executing on host *: undefined method `execute' for main:Object
> 
> …
> Fix undefined method 'as' on Capistrano::Puma and 'execute' should be wrapped in an 'on' block

- lib/capistrano/puma/jungle.rb
- lib/capistrano/tasks/jungle.rake
- lib/capistrano/templates/puma-deb.erb
- lib/capistrano/templates/run-puma.erb
Fix `Warning: `execute' should be wrapped ` in jungle:setup task
Update run-puma to support ruby managment systems.
Update puma-deb from puma repository.
> Fix jungle setup for debian

- lib/capistrano/templates/nginx_conf.erb
Use `$host` instead of `$http_host` to prevent header Host forgery.
https://github.com/yandex/gixy/blob/master/docs/en/plugins/hostspoofing.md
> Use `$host` to prevent forgery

- lib/capistrano/templates/nginx_conf.erb
Force SSL/LTS with return directive
NGINX recommends the return directive over regular expressions.
The return directive is simpler to understand and faster to
execute than the regular expression.
Ref
[1]: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites
[2]: https://www.nginx.com/blog/creating-nginx-rewrite-rules/
Section Example - Forcing all Requests to Use SSL/TLS
> Force SSL/LTS with return directive

- lib/capistrano/tasks/jungle.rake
Explicitly making it refer to the puma config in shared folder so that it won't go and look at the one I use in development environment.
> Added shared puma conf as argument to jungle:add

- README.md
As described in README below fixed string default config file name (path) is:
set :puma_conf, "#{shared_path}/**puma.rb**", not puma.config
> Wrong path to puma config fixed

- lib/capistrano/tasks/puma.rake
Config files were not read due to a typo in the (or possibly outdated) command line parameters.
> Fixed call parameter

- lib/capistrano/templates/nginx_conf.erb
HTTP 1.0 is the default, which doesn't support chunked transfer encoding. This leads to ActiveStorage downloads being truncated.
https://stackoverflow.com/questions/53374839/rails-5-2-1-activestorage-file-downloads-with-nginx-puma-are-truncated/53410174#53410174
> Use HTTP 1.1 for proxying

- README.md
- lib/capistrano/puma/nginx.rb
- lib/capistrano/templates/nginx_conf.erb
setting X-Forwarded-Proto https if ngnix is not using SSL, however, there is SSL termination going on upstream (e.g. AWS ELB)
> special case: setting X-Forwarded-Proto https even if ngnix is not using SSL

- lib/capistrano/tasks/puma.rake
Improves the wording when Puma is already running.
> Improve already running warning message

- README.md
- lib/capistrano/puma/nginx.rb
- lib/capistrano/templates/nginx_conf.erb
Update Nginx template:
- Move obsolete 'ssl' directive to the 'listen' directive instead [http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl)
- Add option to enable http2 for nginx with ssl [http://nginx.org/en/docs/http/ngx_http_v2_module.html](http://nginx.org/en/docs/http/ngx_http_v2_module.html)
> Update nginx template

- CONTRIBUTORS.md
- README.md
- capistrano3-puma.gemspec
- lib/capistrano/puma.rb
- lib/capistrano/puma/systemd.rb
- lib/capistrano/tasks/systemd.rake
- lib/capistrano/templates/puma.service.erb
Fix #297 
Tested with generated puma.rb
Tested with puma 4 and 5 with rvm and rbenv
> Add systemd support and puma 5 support

- lib/capistrano/tasks/daemon.rake
Seems is removed in 24b91a7e1fc9442f9630f1f684885a281feaf1ae original file `lib/capistrano/tasks/puma.rake`, but not add back at new file `lib/capistrano/tasks/daemon.rake`
> Fix #301, Task "puma:smart_restart" not found

- lib/capistrano/tasks/systemd.rake
Rather than having to define a template per staging environment, use
`puma.service` as the template name to lookup.
Fixes seuros/capistrano-puma#305
> Single name for systemd config template

- README.md
- lib/capistrano/puma/systemd.rb
Using a default systemd service name that is consistent with the default
names used in the nginx and monit plugins.
In combination with seuros/capistrano-puma#308, forms a zero-config
solution to seuros/capistrano-puma#305
> Default systemd service name on multi-app host

- lib/capistrano/puma/systemd.rb
- lib/capistrano/tasks/systemd.rake
- lib/capistrano/templates/puma.service.erb
1. fix a problem when setting puma_service_unit_name different from the default value. Before it was unable to use the dafault erb template
2. add puma_service_unit_user config to manage system or user service manager
3. add puma_enable_lingering to anable lingering or not
> Systemd user service manager and lingering

- lib/capistrano/templates/puma.service.erb
This is to fix the error which happens when the service is stopped in systemd.
With the removed line of `ExecStop`, systemd sends a SIGTERM signal to the process when systemd needs to stop it, and the process starts graceful shutdown once the signal is received, but systemd won't wait until the graceful shutdown is done and send another signal of `KillSignal`, whose default value is SIGTERM. Puma graceful shutdown involves removing socket file, but when it receives the 2nd SIGTERM, the socket file has already been deleted, which causes the issue.
To fix that, we could just remove `ExecStop` from systemd file, and let systemd take care of it.
```
/.../ruby/2.5.0/gems/puma-5.1.1/lib/puma/binder.rb:421:in `unlink': No such file or directory @ apply2files - /.../sockets/puma.sock …
```
> Remove ExecStop from systemd unit file

- README.md
- lib/capistrano/puma/systemd.rb
Default to `puma_systemctl_user` to `:system` to avoid a breaking change introduced as part of #307.
> fix: puma_systemctl_user default value

- README.md
- lib/capistrano/puma.rb
- lib/capistrano/puma/systemd.rb
- lib/capistrano/tasks/nginx.rake
- lib/capistrano/tasks/systemd.rake
- lib/capistrano/templates/nginx_conf.erb
- lib/capistrano/templates/puma.service.erb
- lib/capistrano/templates/puma.socket.erb
This PR adds support for using systemd socket activation with Puma. 
I have not yet tested the implementation when using the system user, but this may require that `SocketUser` and `SocketGroup` be specified in the socket file. 
It would be great if you could test it if you have the time @seuros.
When merged this closes #320 
**Tasks**
**PS** I still need to finish some local testing before I can merge, but so far the whole deployment process has run without a hitch!
> Implement puma systemd sockets

- lib/capistrano/puma/systemd.rb
- lib/capistrano/tasks/systemd.rake
- lib/capistrano/templates/puma.service.erb
Added the ability to phased restart puma
Need to define a release directory in config/puma.rb:
`directory '/var/www/current'`
Otherwise, Puma won't pick up your new changes when running phased restarts
> Phased restart

- README.md
- lib/capistrano/puma/systemd.rb
- lib/capistrano/tasks/systemd.rake
As discussed in #329.
Reverted `puma:restart` to be the default. To enable phased restart:
```ruby
set :puma_phased_restart, true
```
I called it `smart_restart` internally as there is the same pattern already for the daemonize plugin.
> Add option for phased restart of puma

- capistrano3-puma.gemspec
capistrano3-puma is the only Capistrano plugin that does it. Use of `install_plugin` is standard - no need to announce it.
> Remove unneeded post-install message

- README.md
After having searched through this gem's history, in order to figure out what was doing that `:puma_init_active_record` parameter, I found that this parameter doesn't exist anymore, therefore this PR removes this README.md section.
> Cleans up the README.md file

- CHANGELOG.md
- README.md
- lib/capistrano/puma/systemd.rb
- lib/capistrano/templates/puma.service.erb
- Added puma_systemd_watchdog_sec configuration option (default: 10)
- Updated systemd template to only include WatchdogSec if value > 0
- Setting to 0 or false disables the watchdog entirely
- Updated README and CHANGELOG to document the new option
This addresses issues with systemd bugs and slow application startup times where the hardcoded 10-second watchdog would kill the puma process.
> Fix #373: Make WatchdogSec configurable
